### ISSUE TITLE
Doesn't initialize on latest HA dev

### ISSUE THREAD

**Issue by tbrasser** [raiyni/ha-actual_budget#1]
```
Logger: homeassistant.setup
Bron: setup.py:334
Eerst voorgekomen: 09:42:15 (1 gebeurtenissen)
Laatst gelogd: 09:42:15

Setup failed for custom integration 'actual_budget': Unable to import component: `pydantic:parse_raw_as` has been removed in V2. For further information visit https://errors.pydantic.dev/2.10/u/import-error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/actual_budget/__init__.py", line 9, in <module>
    from .coordinator import ActualDataUpdateCoordinator
  File "/config/custom_components/actual_budget/coordinator.py", line 11, in <module>
    from .actual_api import ActualApi
  File "/config/custom_components/actual_budget/actual_api.py", line 8, in <module>
    from actual import Actual
  File "/usr/local/lib/python3.13/site-packages/actual/__init__.py", line 40, in <module>
    from actual.queries import (
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/actual/queries.py", line 11, in <module>
    from pydantic import parse_raw_as
  File "/usr/local/lib/python3.13/site-packages/pydantic/__init__.py", line 409, in __getattr__
    return _getattr_migration(attr_name)
  File "/usr/local/lib/python3.13/site-packages/pydantic/_migration.py", line 302, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:parse_raw_as` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.10/u/import-error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/actual_budget/__init__.py", line 9, in <module>
    from .coordinator import ActualDataUpdateCoordinator
  File "/config/custom_components/actual_budget/coordinator.py", line 11, in <module>
    from .actual_api import ActualApi
  File "/config/custom_components/actual_budget/actual_api.py", line 8, in <module>
    from actual import Actual
  File "/usr/local/lib/python3.13/site-packages/actual/__init__.py", line 40, in <module>
    from actual.queries import (
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/actual/queries.py", line 11, in <module>
    from pydantic import parse_raw_as
  File "/usr/local/lib/python3.13/site-packages/pydantic/__init__.py", line 409, in __getattr__
    return _getattr_migration(attr_name)
  File "/usr/local/lib/python3.13/site-packages/pydantic/_migration.py", line 302, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:parse_raw_as` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.10/u/import-error
```

**Comment by raiyni** [comment]
Thank you.

This suggests pydantic has finally migrated to v2 as stated from here https://github.com/home-assistant/core/issues/99218, I didn't think that would happen so soon given the pace they were working on other components.

**Comment by tbrasser** [comment]
FYI https://github.com/jlvcm/ha-actualbudget/releases/tag/v0.1.0

**Comment by raiyni** [comment]
Thank you, I was waiting for 2025.1 to be production as I have many breaking changes on my local side for other integrations.

**Comment by raiyni** [comment]
Currently waiting on a response to https://github.com/bvanelli/actualpy/issues/102

**Comment by bvanelli** [comment]
Thanks for the heads up @raiyni, version [0.8.1](https://github.com/bvanelli/actualpy/releases/tag/0.8.1) has been released.

**Comment by raiyni** [comment]
This should be fixed in https://github.com/raiyni/ha-actual_budget/tree/v0.4.0 now, thank you
